AWSTemplateFormatVersion: '2010-09-09'
Description: NAT Gateway Module

Parameters:
  PublicSubnetId:
    Type: AWS::EC2::Subnet::Id

Resources:
  NatEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatEIP.AllocationId
      SubnetId: !Ref PublicSubnetId
      Tags:
        - Key: Name
          Value: NAT-Gateway

Outputs:
  NatGatewayId:
    Value: !Ref NatGateway
    Description: NAT Gateway ID