AWSTemplateFormatVersion: '2010-09-09'
Description: Create Security Groups for EC2 instances

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id

Resources:
  PublicEC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH from specific IP
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  
      Tags:
        - Key: Name
          Value: PublicEC2SG

  PrivateEC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access from Public EC2 only (no direct SSH)
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref PublicEC2SG
      Tags:
        - Key: Name
          Value: PrivateEC2SG

Outputs:
  PublicSGId:
    Value: !Ref PublicEC2SG
  PrivateSGId:
    Value: !Ref PrivateEC2SG
